[meta]
name = "page"

[title]
description = "A title for the page"
type = "str"
required = true
max_len = 256
min_len = 4

[content]
description = "The content within the page. Will be rendered using markdown."
type = "text"
required = true

[slug]
description = "The url slug that the page will be located at."
